### ISSUE TITLE
[Bug] Camera stream stopped working in 2.2.16

### ISSUE THREAD

**Issue by badnetmask** [greghesp/ha-bambulab#1748]
### Home Assistant Version

2025.12.0

### Bambu Lab Integration Version

v2.2.16

### Describe the bug

This is a formal bug related to an issue [I raised in a discussion](https://github.com/greghesp/ha-bambulab/discussions/1195#discussioncomment-15166537).

The camera stream stopped working in 2.2.16. I'm positive it is in this version, because downgrading to 2.2.14 brings it back.

### To Reproduce

Open the device integration, and there is no camera there.

### Expected Behaviour

Live camera view should work.

### What device are you using?

X1C

### Diagnostic Output

[config_entry-bambu_lab-01JY586BYSA0VFG7WH2MSQNWPD.json](https://github.com/user-attachments/files/23952713/config_entry-bambu_lab-01JY586BYSA0VFG7WH2MSQNWPD.json)

### Log Extracts

```
homeassistant  | 2025-12-04 22:12:18.898 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback BambuDataUpdateCoordinator.event_handler_internal() (None)
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
homeassistant  |     self._context.run(self._callback, *self._args)
homeassistant  |     ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/config/custom_components/bambu_lab/coordinator.py", line 117, in event_handler_internal
homeassistant  |     self._report_live_view_disabled_issue()
homeassistant  |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
homeassistant  |   File "/config/custom_components/bambu_lab/coordinator.py", line 989, in _report_live_view_disabled_issue
homeassistant  |     self._report_generic_issue("live_view_disabled")
homeassistant  |     ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
homeassistant  | TypeError: BambuDataUpdateCoordinator._report_generic_issue() missing 1 required positional argument: 'force'
```

### Other Information

Firmware version 01.11.00.00

**Comment by AdrianGarside** [comment]
And you definitely have lan mode live view enabled? The payload says not and I'm wondering if it's an X1C initialization issue:
        "rtsp_url": "disable",
Or if your X1C has lost that setting. The error is from my refactoring but I'm not sure it explains the non-working camera.

**Comment by AdrianGarside** [comment]
This will fix the error:
https://github.com/greghesp/ha-bambulab/releases/tag/v2.2.17-beta3

**Comment by badnetmask** [comment]
The problem persists even on `2.2.17-beta4`.

Edit: the "_report_generic_issue" problem is gone, but the camera still does not load.

**Comment by AdrianGarside** [comment]
Can you provide a debug log of the integration loading please. And check your printer to confirm lan mode live view is actually still enabled because your diagnostics log says it isn’t.

**Comment by badnetmask** [comment]
Honestly, not sure what happened. I downgraded to 2.2.14 again just to try it out, everything worked, then I upgraded again to 2.2.17-beta4 and now it's working fine.

Do you still need debug information? What else do you need other than the diagnostics file I shared previously?

**Comment by AdrianGarside** [comment]
You may have just hit the fact the X1 RTSP feed is not very reliable. But it’s odd that your diagnostics log showed the RTSP feed disabled by the printer. Now that it’s working can you grab a fresh diagnostics log?

**Comment by badnetmask** [comment]
I believe you're right. I have hit some weird Bambu bug.
I just switched to 2.2.16 again. Now I can see `rtsp_url`, and the camera is working.
I guess I need to keep an eye in my logs and see if I can get a glimpse of what makes the camera fall off the sky?

**Comment by jperquin** [comment]
> 2.2.16

Same here. Reverted to 2.2.16 and camera reappeared while previously on 2.2.18 camera on my X1C also fell off.
