### ISSUE TITLE
[Bug] Integration stopped working after updating HA CORE to 2026.2.0b1

### ISSUE THREAD

**Issue by ReviloEgros** [greghesp/ha-bambulab#1866]
### Home Assistant Version

2026.2.0b1

### Bambu Lab Integration Version

2.2.19

### Describe the bug

After updating HA CORE to 2026.2.0b1 the Integration stopped working. I get errors in the log and Failed to set up on the integrations page.

### To Reproduce

Update HA CORE to 2026.2.0b1

### Expected Behaviour

Integration should work as expected.

### What device are you using?

A1

### Log Extracts

Logger: homeassistant.config_entries
Quelle: config_entries.py:762
Erstmals aufgetreten: 01:43:40 (1 Vorkommnis)
Zuletzt protokolliert: 01:43:40

Error setting up entry XXXXXXXXXXXXXXX for bambu_lab
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 762, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bambu_lab/__init__.py", line 433, in async_setup_entry
    await cards.async_register()
  File "/config/custom_components/bambu_lab/frontend/__init__.py", line 40, in async_register
    if self.lovelace_mode == "storage":
       ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bambu_lab/frontend/__init__.py", line 26, in lovelace_mode
    return self.hass.data["lovelace"].mode
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'LovelaceData' object has no attribute 'mode'

Logger: homeassistant
Quelle: config_entries.py:2616
Erstmals aufgetreten: 01:43:42 (1 Vorkommnis)
Zuletzt protokolliert: 01:43:42

Error doing job: Task exception was never retrieved (task: None)
Traceback (most recent call last):
  File "/config/custom_components/bambu_lab/coordinator.py", line 753, in _reinitialize_sensors
    await self.hass.config_entries.async_forward_entry_setups(self.config_entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2616, in async_forward_entry_setups
    raise OperationNotAllowed(
    ...<4 lines>...
    )
homeassistant.config_entries.OperationNotAllowed: The config entry 'XXXXXXXXXXXXXXX' (bambu_lab) with entry_id '01JENM82FAVM2FD16V0JNKXR5K' cannot forward setup for (<EntityPlatforms.BINARY_SENSOR: 'binary_sensor'>, <EntityPlatforms.BUTTON: 'button'>, <EntityPlatforms.CAMERA: 'camera'>, <EntityPlatforms.FAN: 'fan'>, <EntityPlatforms.IMAGE: 'image'>, <EntityPlatforms.LIGHT: 'light'>, <EntityPlatforms.NUMBER: 'number'>, <EntityPlatforms.SELECT: 'select'>, <EntityPlatforms.SENSOR: 'sensor'>, <EntityPlatforms.SWITCH: 'switch'>, <EntityPlatforms.UPDATE: 'update'>) because it is in state ConfigEntryState.SETUP_ERROR, but needs to be in the ConfigEntryState.LOADED state

**Comment by ReviloEgros** [comment]
Oh, I just noticed that there’s a pull request. Pull request #1865 fixes this bug! Everything is working again as it should.

**Comment by Uber1337NL** [comment]
Tested the PR. That indeed fixed the issue introduces in 2026.2. Thanks for the quick-fix Paul!

**Comment by Jan-Wenner** [comment]
How can I install the PR Version?

**Comment by AdrianGarside** [comment]
https://github.com/greghesp/ha-bambulab/releases/tag/v2.2.20-beta3

**Comment by lazyboy0172** [comment]
I'm actually still having the issue on 2.2.20-beta3 (and beta4), though slightly different now:

  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 762, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bambu_lab/__init__.py", line 433, in async_setup_entry
    await cards.async_register()
  File "/config/custom_components/bambu_lab/frontend/__init__.py", line 44, in async_register
    if self.lovelace_resource_mode == "storage":
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bambu_lab/frontend/__init__.py", line 28, in lovelace_resource_mode
    if compare_version(__version__, "2026.2.0") >= 0:
       ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bambu_lab/pybambu/utils.py", line 327, in compare_version
    maxver = list(map(int, version_max.split('.')))
ValueError: invalid literal for int() with base 10: '0b1'


seems to be related to being on beta branch that my subversion is not 2026.2.0 but instead 2026.2.0b1

Won't be a problem for users that are never on a beta branch, but will almost always be an issue for users on a beta branch.

**Comment by AdrianGarside** [comment]
Ah. I will make a fix for that.

**Comment by Siebe-Uy** [comment]
> I'm actually still having the issue on 2.2.20-beta3 (and beta4), though slightly different now:
> 
> File "/usr/src/homeassistant/homeassistant/config_entries.py", line 762, in __async_setup_with_context result = await component.async_setup_entry(hass, self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/bambu_lab/**init**.py", line 433, in async_setup_entry await cards.async_register() File "/config/custom_components/bambu_lab/frontend/**init**.py", line 44, in async_register if self.lovelace_resource_mode == "storage": ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/bambu_lab/frontend/**init**.py", line 28, in lovelace_resource_mode if compare_version(**version**, "2026.2.0") >= 0: ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/bambu_lab/pybambu/utils.py", line 327, in compare_version maxver = list(map(int, version_max.split('.'))) ValueError: invalid literal for int() with base 10: '0b1'
> 
> seems to be related to being on beta branch that my subversion is not 2026.2.0 but instead 2026.2.0b1
> 
> Won't be a problem for users that are never on a beta branch, but will almost always be an issue for users on a beta branch.

Same problem here

**Comment by lazyboy0172** [comment]
good PR @Switchbot-Nova . I manually edited the file in my install and was able to get back up and running, controls work and correctly pulling current status of my p1s and ams2pro.

**Comment by dmosleyx** [comment]
I just updated to HA 2026.2.0 and I am also having this issue. It's a failed to set up under 'Devices and Integrations', and when I try to re-set it up it says 'failed to connect' after plugging in all the relevant information such as access code and IP address.
