### ISSUE TITLE
[Feature] Add time lapse sensor or attribute

### ISSUE THREAD

**Issue by renssies** [greghesp/ha-bambulab#105]
### Describe the feature

My printer is in a space that has the light automatically turn off when there is no motion. 
However while recording a time lapse I want to disable that automation. 

So it would be great to have a sensor or even an attribute that checks if timelapse is turned on for the current print.

### What device is this for?

X1C

### Other Information

The X1C reports this in the ipcam section of the report MQTT message.
```JSON
{
    "print": {
        ....
        "ipcam": {
            "ipcam_dev": "1",
            "ipcam_record": "enable",
            "resolution": "720p",
            "timelapse": "disable"
        },
        "layer_num": 0,
        "lifecycle": "product",
        "lights_report": [
            {
                "mode": "on",
                "node": "chamber_light"
            },
            {
                "mode": "flashing",
                "node": "work_light"
            }
        ],
       ....
    }
}

**Comment by AdrianGarside** [comment]
I have everything except the resolution:
```
    "ipcam": {
      "ipcam_dev": "1",
      "ipcam_record": "enable",
      "timelapse": "disable"
    },
```

**Comment by AdrianGarside** [comment]
https://github.com/greghesp/ha-bambulab/releases/tag/v1.1.1-dev2

**Comment by renssies** [comment]
Something was going on with the printer, halfway through a print it suddenly threw the error that the build plate marker was not found and stopped. So something in the firmware made a mistake.

After power cycling the printer and trying again I can confirm it is working now, when it starts the actual printing process it turns to `enable` and after the print goes back to `disable`.

So I would still propose to make this a `binary_sensor`, name it "Recording Timelapse" where `on/true` = enable and `off/false` = disable

**Comment by renssies** [comment]
Hmm this seems to have broken in 1.1.1-dev3. 

The old timelapse entity is now gone (which I suspected), but I'm getting an error and the new one never appears. 

![Screenshot 2023-04-22 at 02 23 56](https://user-images.githubusercontent.com/830094/233751862-487ed8ba-fcad-45fc-b491-0fcfbd99f2eb.png)

Log entry
```
Logger: homeassistant.setup
Source: setup.py:347 
First occurred: 2:23:46 AM (1 occurrences) 
Last logged: 2:23:46 AM

Unable to prepare setup for platform bambu_lab.binary_sensor: Platform not found (cannot import name 'PRINTER_BINARY_SENSORS' from 'custom_components.bambu_lab.definitions' (/config/custom_components/bambu_lab/definitions.py)).
```

**Comment by AdrianGarside** [comment]
I had a bad merge that lost changes from that file. Fixing now.

**Comment by AdrianGarside** [comment]
https://github.com/greghesp/ha-bambulab/releases/tag/v1.1.1-dev4

**Comment by renssies** [comment]
In 1.1.1-dev5 this one seems to be broken, it does appear now, but MQTT reports `"timelapse": "enable"` however the sensor is still "Not running"

![Screenshot 2023-04-22 at 14 07 28](https://user-images.githubusercontent.com/830094/233783752-743262cc-7558-458a-a5b5-4eaa20625ef6.png)

**Comment by AdrianGarside** [comment]
Ok, I wasn't able to test the latest drops since my printer was being slightly disassembled to install an mc board fan. Let me kick off a test print and see what's going on.

**Comment by renssies** [comment]
I just noticed nothing has really updated, so I assume it was similar to the progress issue #115

**Comment by AdrianGarside** [comment]
That was specific to just these two values which were in the wrong update method after some refactoring I did:
        self.wifi_signal = int(data.get("wifi_signal", str(self.wifi_signal)).replace("dBm", ""))
        self.print_percentage = data.get("mc_percent", self.print_percentage)

**Comment by AdrianGarside** [comment]
If nothing is updating live, then that could be #92 which we haven't been able to repro and don't understand.

**Comment by AdrianGarside** [comment]
Ok, found the issue with the timelapse. Fix coming.

**Comment by AdrianGarside** [comment]
https://github.com/greghesp/ha-bambulab/releases/tag/v1.1.1-dev8

**Comment by renssies** [comment]
This now works in 1.1.1-dev8 indeed! 👍
