### ISSUE TITLE
[Bug] Integration doesn't work with HA 2026.2

### ISSUE THREAD

**Issue by Ciredm** [greghesp/ha-bambulab#1886]
### Home Assistant Version

2026.2.1

### Bambu Lab Integration Version

v2.2.19

### Describe the bug

Bambu Integration doesn't load after update to 2026.2. Revert to 2026.1 solve this issue.

### To Reproduce

Update to HA 2026.2
On Rpi 3 with HassOS

### Expected Behaviour

Integration doesn't load

### What device are you using?

A1

### Diagnostic Output

Frontend no data
Integration error when loading

### Log Extracts

Enregistreur: homeassistant.config_entries
Source: config_entries.py:762
S'est produit pour la première fois: 13:55:36 (1 occurrence)
Dernier enregistrement: 13:55:36

Error setting up entry 03xxxxxxxxxx for bambu_lab
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 762, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bambu_lab/__init__.py", line 433, in async_setup_entry
    await cards.async_register()
  File "/config/custom_components/bambu_lab/frontend/__init__.py", line 40, in async_register
    if self.lovelace_mode == "storage":
       ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bambu_lab/frontend/__init__.py", line 26, in lovelace_mode
    return self.hass.data["lovelace"].mode
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'LovelaceData' object has no attribute 'mode'

**Comment by AdrianGarside** [comment]
Upgrade

**Comment by Ciredm** [comment]
Ok, sorry, due to manipulation error, I don't see any notification of upgrade (no information of new version in hacs).

Thanks
